#! /bin/sh

# file: /lib/systemd/system-shutdown/picade-hat-poweroff
# $1 will be either "halt", "poweroff", "reboot" or "kexec"

case "$1" in
  poweroff)
        /bin/echo 4 > /sys/class/gpio/export
        /bin/echo out > /sys/class/gpio/gpio4/direction
        /bin/echo 0 > /sys/class/gpio/gpio4/value
        /bin/sleep 0.5
        ;;
esac

: